### ISSUE TITLE
small demo

### ISSUE THREAD

**Issue by rbosneag** [andrewrabon/concrete-elements#4]
Before launching your _marketing_ site, it would be nice to show a few samples of your components.   It may be useful and attractive for newcomers, don't you think?

**Comment by andrewrabon** [comment]
Good point! That's also been in progress, and you can see it here: example.concrete-elements.org.

I still need to flesh that out even more, though.

**Comment by andrewrabon** [comment]
I should have also been clearer that the "marketing" site will host documentation and examples (concrete-elements.org.)

The example site above has been repurposed -- it's not an empty "starter" project using Concrete to hit the ground running. The URL has been updated to https://starter.concrete-elements.org, with the repo at https://github.com/andrewrabon/concrete-starter-app

I'm marking this as a dupe since its purpose is the same as getting the main concrete-elements.org site up and running, but the message has been heard loud and clear.

**Comment by andrewrabon** [comment]
To answer OP @rbosneag, https://concrete-elements.org is now live with examples and a very light amount of documentation (currently.) Work is underway on fleshing it out in time for the upcoming 1.0.0 stable release.
